---
authors:
  - Rohit Thakur (rohitthakur2590)
  - Aayush Anand  (AAYUSH2091)
dependencies:
  "ansible.netcommon": ">=6.0.0"
  "ansible.utils": ">=3.0.0"
  "ansible.scm": ">=2.0.0"
  "containers.podman": ">=1.0.0"
license_file: LICENSE
name: reports
description: Ansible Network BGP enables users to manage the BGP resources independently of platforms and perform BGP health checks.
namespace: network
readme: README.md
repository: https://github.com/ansible-network/network.reports
issues: https://github.com/ansible-network/network.reports/issues
tags: [networking]
version: 1.0.0
