- name: Parse show version
  ansible.utils.cli_parse:
    command: "show version"
    parser:
      name: ansible.netcommon.native
    set_fact: version_data

- name: Parse hostname
  ansible.utils.cli_parse:
    command: "sh running-config | include hostname"
    parser:
      name: ansible.netcommon.native
    set_fact: hostname_resources

- name: Parse license
  ansible.utils.cli_parse:
    command: "show license all"
    parser:
      name: ansible.netcommon.native
    set_fact: license_data
  ignore_errors: true

- name: Parse Memory
  ansible.utils.cli_parse:
    command: "show memory summary"
    parser:
      name: ansible.netcommon.native
    set_fact: memory_resources

# Combine all into one system_resources
- name: Combine all resources into system_resources
  ansible.builtin.set_fact:
    system_resources: >-
      {{
        version_data
        | combine(hostname_resources, recursive=True)
        | combine(license_data | default({}), recursive=True)
        | combine(memory_resources, recursive=True)
      }}
