---
- name: Set target hosts fact
  ansible.builtin.set_fact:
    report_target_hosts: "{{ ansible_play_hosts }}"
  run_once: true
  delegate_to: localhost

- name: Creates directory
  ansible.builtin.file:
    path: "{{ generate_report_file_path }}"
    state: directory
    mode: "0777"
    recurse: true
  become: true
  delegate_to: localhost

- name: Ensure Nginx container is running
  containers.podman.podman_container:
    name: nginx_container
    image: docker.io/nginx:stable-alpine3.17-slim
    state: started
    ports:
      - "{{ generate_report_web_port }}:80"
    volumes:
      - "{{ generate_report_file_path }}:/usr/share/nginx/html:Z"
    recreate: true

- name: Create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ generate_report_file_path }}/index.html"
    mode: "0777"
  vars:
    target_hosts: "{{ report_target_hosts | list }}"
  delegate_to: localhost

- name: Copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ generate_report_file_path }}"
    directory_mode: true
    mode: "0777"
  delegate_to: localhost

- name: Copy CSS over
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ generate_report_file_path }}"
    directory_mode: true
    mode: "0777"
  delegate_to: localhost
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"

- name: Retrieve public IP address
  ansible.builtin.uri:
    url: https://ifconfig.me
    return_content: true
  register: public_ip_report
  failed_when: public_ip_report.status != 200
  changed_when: false

- name: Extract IP address from HTML
  ansible.builtin.set_fact:
    extracted_ip: "{{ (public_ip_report.content | regex_search('<strong id=\"ip_address\">\\s*([^\\s<]+)', '\\1') | first) | default(ansible_fqdn) }}"
  when: not public_ip_report.failed

- name: Display link to inventory report
  ansible.builtin.debug:
    msg:
      - "Please go to http://{{ extracted_ip | default(ansible_fqdn) }}:{{ generate_report_web_port }}"
