- name: "memory_summary_physical_total"
  getval: "\\sPhysical Memory:\\s+(?P<physical_total>\\d+M)\\s+total"
  result:
    memory:
      total_mb: "{{ physical_total }}"

- name: "memory_summary_app_total"
  getval: "\\sApplication\\sMemory\\s:\\s\\d+M\\s\\((?P<free>\\d+M)\\savailable\\)"
  result:
    memory:
      free_mb: "{{ free }}"

- name: "memory_summary_image_size"
  getval: "\\sImage:\\s+(?P<image_size>\\d+M)"
  result:
    memory_summary:
      image_size: "{{ image_size }}"
