---
- name: Include tasks {{ ansible_network_os.split('.')[2] }}
  ansible.builtin.include_tasks: ./{{ ansible_network_os.split('.')[2] }}.yaml

- name: Display resource facts
  ansible.builtin.debug:
    msg: "{{ persist_result }}"
