---
- name: Ensure inventory directory exists
  ansible.builtin.file:
    path: "{{ persist_inventory_path }}/host_vars/{{ inventory_hostname }}"
    state: directory
    mode: "0777"
  delegate_to: localhost

- name: Initialize persist_results if empty
  ansible.builtin.set_fact:
    persist_results: "{{ persist_result }}"
- name: Write persist resource to a file
  ansible.builtin.copy:
    content: "{{ persist_results }}"
    dest: "{{ persist_inventory_path }}/host_vars/{{ inventory_hostname }}.yaml"
    mode: "0777"
  delegate_to: localhost
